//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityCommunities.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KonferansSalonlari", Namespace="http://schemas.datacontract.org/2004/07/UniversityCommunities.Models")]
    [System.SerializableAttribute()]
    public partial class KonferansSalonlari : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UniversityCommunities.ServiceReference1.KulupEtkinlikleri[] KulupEtkinlikleriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalonAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UniversityCommunities.ServiceReference1.KulupEtkinlikleri[] KulupEtkinlikleri {
            get {
                return this.KulupEtkinlikleriField;
            }
            set {
                if ((object.ReferenceEquals(this.KulupEtkinlikleriField, value) != true)) {
                    this.KulupEtkinlikleriField = value;
                    this.RaisePropertyChanged("KulupEtkinlikleri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SalonAdi {
            get {
                return this.SalonAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.SalonAdiField, value) != true)) {
                    this.SalonAdiField = value;
                    this.RaisePropertyChanged("SalonAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KulupEtkinlikleri", Namespace="http://schemas.datacontract.org/2004/07/UniversityCommunities.Models")]
    [System.SerializableAttribute()]
    public partial class KulupEtkinlikleri : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UniversityCommunities.ServiceReference1.EtkinlikTurleri EtkinlikTurleriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Etkinlik_AdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Etkinlik_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Etkinlik_KonusuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> Etkinlik_TarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> Etkinlik_Turu_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UniversityCommunities.ServiceReference1.FaaliyetTurleri FaaliyetTurleriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> Faaliyet_Turu_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UniversityCommunities.ServiceReference1.KonferansSalonlari KonferansSalonlariField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UniversityCommunities.ServiceReference1.KulupEtkinlikFotograflari[] KulupEtkinlikFotograflariField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UniversityCommunities.ServiceReference1.KulupKayit KulupKayitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Kulup_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> OnayDurumuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SalonIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> isVisibleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adres {
            get {
                return this.AdresField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresField, value) != true)) {
                    this.AdresField = value;
                    this.RaisePropertyChanged("Adres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UniversityCommunities.ServiceReference1.EtkinlikTurleri EtkinlikTurleri {
            get {
                return this.EtkinlikTurleriField;
            }
            set {
                if ((object.ReferenceEquals(this.EtkinlikTurleriField, value) != true)) {
                    this.EtkinlikTurleriField = value;
                    this.RaisePropertyChanged("EtkinlikTurleri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Etkinlik_Adi {
            get {
                return this.Etkinlik_AdiField;
            }
            set {
                if ((object.ReferenceEquals(this.Etkinlik_AdiField, value) != true)) {
                    this.Etkinlik_AdiField = value;
                    this.RaisePropertyChanged("Etkinlik_Adi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Etkinlik_Id {
            get {
                return this.Etkinlik_IdField;
            }
            set {
                if ((this.Etkinlik_IdField.Equals(value) != true)) {
                    this.Etkinlik_IdField = value;
                    this.RaisePropertyChanged("Etkinlik_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Etkinlik_Konusu {
            get {
                return this.Etkinlik_KonusuField;
            }
            set {
                if ((object.ReferenceEquals(this.Etkinlik_KonusuField, value) != true)) {
                    this.Etkinlik_KonusuField = value;
                    this.RaisePropertyChanged("Etkinlik_Konusu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Etkinlik_Tarihi {
            get {
                return this.Etkinlik_TarihiField;
            }
            set {
                if ((this.Etkinlik_TarihiField.Equals(value) != true)) {
                    this.Etkinlik_TarihiField = value;
                    this.RaisePropertyChanged("Etkinlik_Tarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> Etkinlik_Turu_Id {
            get {
                return this.Etkinlik_Turu_IdField;
            }
            set {
                if ((this.Etkinlik_Turu_IdField.Equals(value) != true)) {
                    this.Etkinlik_Turu_IdField = value;
                    this.RaisePropertyChanged("Etkinlik_Turu_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UniversityCommunities.ServiceReference1.FaaliyetTurleri FaaliyetTurleri {
            get {
                return this.FaaliyetTurleriField;
            }
            set {
                if ((object.ReferenceEquals(this.FaaliyetTurleriField, value) != true)) {
                    this.FaaliyetTurleriField = value;
                    this.RaisePropertyChanged("FaaliyetTurleri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> Faaliyet_Turu_Id {
            get {
                return this.Faaliyet_Turu_IdField;
            }
            set {
                if ((this.Faaliyet_Turu_IdField.Equals(value) != true)) {
                    this.Faaliyet_Turu_IdField = value;
                    this.RaisePropertyChanged("Faaliyet_Turu_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UniversityCommunities.ServiceReference1.KonferansSalonlari KonferansSalonlari {
            get {
                return this.KonferansSalonlariField;
            }
            set {
                if ((object.ReferenceEquals(this.KonferansSalonlariField, value) != true)) {
                    this.KonferansSalonlariField = value;
                    this.RaisePropertyChanged("KonferansSalonlari");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UniversityCommunities.ServiceReference1.KulupEtkinlikFotograflari[] KulupEtkinlikFotograflari {
            get {
                return this.KulupEtkinlikFotograflariField;
            }
            set {
                if ((object.ReferenceEquals(this.KulupEtkinlikFotograflariField, value) != true)) {
                    this.KulupEtkinlikFotograflariField = value;
                    this.RaisePropertyChanged("KulupEtkinlikFotograflari");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UniversityCommunities.ServiceReference1.KulupKayit KulupKayit {
            get {
                return this.KulupKayitField;
            }
            set {
                if ((object.ReferenceEquals(this.KulupKayitField, value) != true)) {
                    this.KulupKayitField = value;
                    this.RaisePropertyChanged("KulupKayit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Kulup_Id {
            get {
                return this.Kulup_IdField;
            }
            set {
                if ((this.Kulup_IdField.Equals(value) != true)) {
                    this.Kulup_IdField = value;
                    this.RaisePropertyChanged("Kulup_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> OnayDurumu {
            get {
                return this.OnayDurumuField;
            }
            set {
                if ((this.OnayDurumuField.Equals(value) != true)) {
                    this.OnayDurumuField = value;
                    this.RaisePropertyChanged("OnayDurumu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SalonId {
            get {
                return this.SalonIdField;
            }
            set {
                if ((this.SalonIdField.Equals(value) != true)) {
                    this.SalonIdField = value;
                    this.RaisePropertyChanged("SalonId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> isVisible {
            get {
                return this.isVisibleField;
            }
            set {
                if ((this.isVisibleField.Equals(value) != true)) {
                    this.isVisibleField = value;
                    this.RaisePropertyChanged("isVisible");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EtkinlikTurleri", Namespace="http://schemas.datacontract.org/2004/07/UniversityCommunities.Models")]
    [System.SerializableAttribute()]
    public partial class EtkinlikTurleri : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Etkinlik_Turu_AdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short Etkinlik_Turu_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UniversityCommunities.ServiceReference1.KulupEtkinlikleri[] KulupEtkinlikleriField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Etkinlik_Turu_Adi {
            get {
                return this.Etkinlik_Turu_AdiField;
            }
            set {
                if ((object.ReferenceEquals(this.Etkinlik_Turu_AdiField, value) != true)) {
                    this.Etkinlik_Turu_AdiField = value;
                    this.RaisePropertyChanged("Etkinlik_Turu_Adi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Etkinlik_Turu_Id {
            get {
                return this.Etkinlik_Turu_IdField;
            }
            set {
                if ((this.Etkinlik_Turu_IdField.Equals(value) != true)) {
                    this.Etkinlik_Turu_IdField = value;
                    this.RaisePropertyChanged("Etkinlik_Turu_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UniversityCommunities.ServiceReference1.KulupEtkinlikleri[] KulupEtkinlikleri {
            get {
                return this.KulupEtkinlikleriField;
            }
            set {
                if ((object.ReferenceEquals(this.KulupEtkinlikleriField, value) != true)) {
                    this.KulupEtkinlikleriField = value;
                    this.RaisePropertyChanged("KulupEtkinlikleri");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaaliyetTurleri", Namespace="http://schemas.datacontract.org/2004/07/UniversityCommunities.Models")]
    [System.SerializableAttribute()]
    public partial class FaaliyetTurleri : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Faaliyet_Turu_AdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short Faaliyet_Turu_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UniversityCommunities.ServiceReference1.KulupEtkinlikleri[] KulupEtkinlikleriField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Faaliyet_Turu_Adi {
            get {
                return this.Faaliyet_Turu_AdiField;
            }
            set {
                if ((object.ReferenceEquals(this.Faaliyet_Turu_AdiField, value) != true)) {
                    this.Faaliyet_Turu_AdiField = value;
                    this.RaisePropertyChanged("Faaliyet_Turu_Adi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Faaliyet_Turu_Id {
            get {
                return this.Faaliyet_Turu_IdField;
            }
            set {
                if ((this.Faaliyet_Turu_IdField.Equals(value) != true)) {
                    this.Faaliyet_Turu_IdField = value;
                    this.RaisePropertyChanged("Faaliyet_Turu_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UniversityCommunities.ServiceReference1.KulupEtkinlikleri[] KulupEtkinlikleri {
            get {
                return this.KulupEtkinlikleriField;
            }
            set {
                if ((object.ReferenceEquals(this.KulupEtkinlikleriField, value) != true)) {
                    this.KulupEtkinlikleriField = value;
                    this.RaisePropertyChanged("KulupEtkinlikleri");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KulupKayit", Namespace="http://schemas.datacontract.org/2004/07/UniversityCommunities.Models")]
    [System.SerializableAttribute()]
    public partial class KulupKayit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Fakulte_NoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UniversityCommunities.ServiceReference1.Fakulteler FakultelerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KulupDanisman_AdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KulupDanisman_MailAdresiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KulupDanisman_SoyadiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KulupDanisman_TelefonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KulupDanisman_UnvaniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UniversityCommunities.ServiceReference1.KulupEtkinlikleri[] KulupEtkinlikleriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UniversityCommunities.ServiceReference1.KulupGuvenlikBilgileri[] KulupGuvenlikBilgileriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UniversityCommunities.ServiceReference1.KulupLogo[] KulupLogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Kulup_AdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Kulup_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Kulup_KurulusAmaciField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> OnayDurumuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UniversityCommunities.ServiceReference1.UniversiteKayit UniversiteKayitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Universite_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UniversityCommunities.ServiceReference1.Uyeler[] UyelerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> isVisibleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Fakulte_No {
            get {
                return this.Fakulte_NoField;
            }
            set {
                if ((this.Fakulte_NoField.Equals(value) != true)) {
                    this.Fakulte_NoField = value;
                    this.RaisePropertyChanged("Fakulte_No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UniversityCommunities.ServiceReference1.Fakulteler Fakulteler {
            get {
                return this.FakultelerField;
            }
            set {
                if ((object.ReferenceEquals(this.FakultelerField, value) != true)) {
                    this.FakultelerField = value;
                    this.RaisePropertyChanged("Fakulteler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KulupDanisman_Adi {
            get {
                return this.KulupDanisman_AdiField;
            }
            set {
                if ((object.ReferenceEquals(this.KulupDanisman_AdiField, value) != true)) {
                    this.KulupDanisman_AdiField = value;
                    this.RaisePropertyChanged("KulupDanisman_Adi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KulupDanisman_MailAdresi {
            get {
                return this.KulupDanisman_MailAdresiField;
            }
            set {
                if ((object.ReferenceEquals(this.KulupDanisman_MailAdresiField, value) != true)) {
                    this.KulupDanisman_MailAdresiField = value;
                    this.RaisePropertyChanged("KulupDanisman_MailAdresi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KulupDanisman_Soyadi {
            get {
                return this.KulupDanisman_SoyadiField;
            }
            set {
                if ((object.ReferenceEquals(this.KulupDanisman_SoyadiField, value) != true)) {
                    this.KulupDanisman_SoyadiField = value;
                    this.RaisePropertyChanged("KulupDanisman_Soyadi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KulupDanisman_Telefon {
            get {
                return this.KulupDanisman_TelefonField;
            }
            set {
                if ((object.ReferenceEquals(this.KulupDanisman_TelefonField, value) != true)) {
                    this.KulupDanisman_TelefonField = value;
                    this.RaisePropertyChanged("KulupDanisman_Telefon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KulupDanisman_Unvani {
            get {
                return this.KulupDanisman_UnvaniField;
            }
            set {
                if ((object.ReferenceEquals(this.KulupDanisman_UnvaniField, value) != true)) {
                    this.KulupDanisman_UnvaniField = value;
                    this.RaisePropertyChanged("KulupDanisman_Unvani");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UniversityCommunities.ServiceReference1.KulupEtkinlikleri[] KulupEtkinlikleri {
            get {
                return this.KulupEtkinlikleriField;
            }
            set {
                if ((object.ReferenceEquals(this.KulupEtkinlikleriField, value) != true)) {
                    this.KulupEtkinlikleriField = value;
                    this.RaisePropertyChanged("KulupEtkinlikleri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UniversityCommunities.ServiceReference1.KulupGuvenlikBilgileri[] KulupGuvenlikBilgileri {
            get {
                return this.KulupGuvenlikBilgileriField;
            }
            set {
                if ((object.ReferenceEquals(this.KulupGuvenlikBilgileriField, value) != true)) {
                    this.KulupGuvenlikBilgileriField = value;
                    this.RaisePropertyChanged("KulupGuvenlikBilgileri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UniversityCommunities.ServiceReference1.KulupLogo[] KulupLogo {
            get {
                return this.KulupLogoField;
            }
            set {
                if ((object.ReferenceEquals(this.KulupLogoField, value) != true)) {
                    this.KulupLogoField = value;
                    this.RaisePropertyChanged("KulupLogo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kulup_Adi {
            get {
                return this.Kulup_AdiField;
            }
            set {
                if ((object.ReferenceEquals(this.Kulup_AdiField, value) != true)) {
                    this.Kulup_AdiField = value;
                    this.RaisePropertyChanged("Kulup_Adi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Kulup_Id {
            get {
                return this.Kulup_IdField;
            }
            set {
                if ((this.Kulup_IdField.Equals(value) != true)) {
                    this.Kulup_IdField = value;
                    this.RaisePropertyChanged("Kulup_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kulup_KurulusAmaci {
            get {
                return this.Kulup_KurulusAmaciField;
            }
            set {
                if ((object.ReferenceEquals(this.Kulup_KurulusAmaciField, value) != true)) {
                    this.Kulup_KurulusAmaciField = value;
                    this.RaisePropertyChanged("Kulup_KurulusAmaci");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> OnayDurumu {
            get {
                return this.OnayDurumuField;
            }
            set {
                if ((this.OnayDurumuField.Equals(value) != true)) {
                    this.OnayDurumuField = value;
                    this.RaisePropertyChanged("OnayDurumu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UniversityCommunities.ServiceReference1.UniversiteKayit UniversiteKayit {
            get {
                return this.UniversiteKayitField;
            }
            set {
                if ((object.ReferenceEquals(this.UniversiteKayitField, value) != true)) {
                    this.UniversiteKayitField = value;
                    this.RaisePropertyChanged("UniversiteKayit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Universite_Id {
            get {
                return this.Universite_IdField;
            }
            set {
                if ((this.Universite_IdField.Equals(value) != true)) {
                    this.Universite_IdField = value;
                    this.RaisePropertyChanged("Universite_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UniversityCommunities.ServiceReference1.Uyeler[] Uyeler {
            get {
                return this.UyelerField;
            }
            set {
                if ((object.ReferenceEquals(this.UyelerField, value) != true)) {
                    this.UyelerField = value;
                    this.RaisePropertyChanged("Uyeler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> isVisible {
            get {
                return this.isVisibleField;
            }
            set {
                if ((this.isVisibleField.Equals(value) != true)) {
                    this.isVisibleField = value;
                    this.RaisePropertyChanged("isVisible");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KulupEtkinlikFotograflari", Namespace="http://schemas.datacontract.org/2004/07/UniversityCommunities.Models")]
    [System.SerializableAttribute()]
    public partial class KulupEtkinlikFotograflari : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EtkinlikIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FotoAçıklamaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FotoBaşlıkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FotoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FotoURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UniversityCommunities.ServiceReference1.KulupEtkinlikleri KulupEtkinlikleriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> isVisibleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EtkinlikId {
            get {
                return this.EtkinlikIdField;
            }
            set {
                if ((this.EtkinlikIdField.Equals(value) != true)) {
                    this.EtkinlikIdField = value;
                    this.RaisePropertyChanged("EtkinlikId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FotoAçıklama {
            get {
                return this.FotoAçıklamaField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoAçıklamaField, value) != true)) {
                    this.FotoAçıklamaField = value;
                    this.RaisePropertyChanged("FotoAçıklama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FotoBaşlık {
            get {
                return this.FotoBaşlıkField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoBaşlıkField, value) != true)) {
                    this.FotoBaşlıkField = value;
                    this.RaisePropertyChanged("FotoBaşlık");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FotoId {
            get {
                return this.FotoIdField;
            }
            set {
                if ((this.FotoIdField.Equals(value) != true)) {
                    this.FotoIdField = value;
                    this.RaisePropertyChanged("FotoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FotoURL {
            get {
                return this.FotoURLField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoURLField, value) != true)) {
                    this.FotoURLField = value;
                    this.RaisePropertyChanged("FotoURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UniversityCommunities.ServiceReference1.KulupEtkinlikleri KulupEtkinlikleri {
            get {
                return this.KulupEtkinlikleriField;
            }
            set {
                if ((object.ReferenceEquals(this.KulupEtkinlikleriField, value) != true)) {
                    this.KulupEtkinlikleriField = value;
                    this.RaisePropertyChanged("KulupEtkinlikleri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> isVisible {
            get {
                return this.isVisibleField;
            }
            set {
                if ((this.isVisibleField.Equals(value) != true)) {
                    this.isVisibleField = value;
                    this.RaisePropertyChanged("isVisible");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fakulteler", Namespace="http://schemas.datacontract.org/2004/07/UniversityCommunities.Models")]
    [System.SerializableAttribute()]
    public partial class Fakulteler : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UniversityCommunities.ServiceReference1.Bolumler[] BolumlerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Fakulte_AdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Fakulte_NoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UniversityCommunities.ServiceReference1.KulupKayit[] KulupKayitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UniversityCommunities.ServiceReference1.Uyeler[] UyelerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UniversityCommunities.ServiceReference1.Bolumler[] Bolumler {
            get {
                return this.BolumlerField;
            }
            set {
                if ((object.ReferenceEquals(this.BolumlerField, value) != true)) {
                    this.BolumlerField = value;
                    this.RaisePropertyChanged("Bolumler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fakulte_Adi {
            get {
                return this.Fakulte_AdiField;
            }
            set {
                if ((object.ReferenceEquals(this.Fakulte_AdiField, value) != true)) {
                    this.Fakulte_AdiField = value;
                    this.RaisePropertyChanged("Fakulte_Adi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Fakulte_No {
            get {
                return this.Fakulte_NoField;
            }
            set {
                if ((this.Fakulte_NoField.Equals(value) != true)) {
                    this.Fakulte_NoField = value;
                    this.RaisePropertyChanged("Fakulte_No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UniversityCommunities.ServiceReference1.KulupKayit[] KulupKayit {
            get {
                return this.KulupKayitField;
            }
            set {
                if ((object.ReferenceEquals(this.KulupKayitField, value) != true)) {
                    this.KulupKayitField = value;
                    this.RaisePropertyChanged("KulupKayit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UniversityCommunities.ServiceReference1.Uyeler[] Uyeler {
            get {
                return this.UyelerField;
            }
            set {
                if ((object.ReferenceEquals(this.UyelerField, value) != true)) {
                    this.UyelerField = value;
                    this.RaisePropertyChanged("Uyeler");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UniversiteKayit", Namespace="http://schemas.datacontract.org/2004/07/UniversityCommunities.Models")]
    [System.SerializableAttribute()]
    public partial class UniversiteKayit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KullaniciAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UniversityCommunities.ServiceReference1.KulupKayit[] KulupKayitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SifreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Universite_AdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Universite_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Universite_KampusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Universite_ilNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Universite_ilceNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> isVisibleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KullaniciAdi {
            get {
                return this.KullaniciAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.KullaniciAdiField, value) != true)) {
                    this.KullaniciAdiField = value;
                    this.RaisePropertyChanged("KullaniciAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UniversityCommunities.ServiceReference1.KulupKayit[] KulupKayit {
            get {
                return this.KulupKayitField;
            }
            set {
                if ((object.ReferenceEquals(this.KulupKayitField, value) != true)) {
                    this.KulupKayitField = value;
                    this.RaisePropertyChanged("KulupKayit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sifre {
            get {
                return this.SifreField;
            }
            set {
                if ((object.ReferenceEquals(this.SifreField, value) != true)) {
                    this.SifreField = value;
                    this.RaisePropertyChanged("Sifre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Universite_Adi {
            get {
                return this.Universite_AdiField;
            }
            set {
                if ((object.ReferenceEquals(this.Universite_AdiField, value) != true)) {
                    this.Universite_AdiField = value;
                    this.RaisePropertyChanged("Universite_Adi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Universite_Id {
            get {
                return this.Universite_IdField;
            }
            set {
                if ((this.Universite_IdField.Equals(value) != true)) {
                    this.Universite_IdField = value;
                    this.RaisePropertyChanged("Universite_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Universite_Kampus {
            get {
                return this.Universite_KampusField;
            }
            set {
                if ((object.ReferenceEquals(this.Universite_KampusField, value) != true)) {
                    this.Universite_KampusField = value;
                    this.RaisePropertyChanged("Universite_Kampus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Universite_ilNo {
            get {
                return this.Universite_ilNoField;
            }
            set {
                if ((this.Universite_ilNoField.Equals(value) != true)) {
                    this.Universite_ilNoField = value;
                    this.RaisePropertyChanged("Universite_ilNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Universite_ilceNo {
            get {
                return this.Universite_ilceNoField;
            }
            set {
                if ((this.Universite_ilceNoField.Equals(value) != true)) {
                    this.Universite_ilceNoField = value;
                    this.RaisePropertyChanged("Universite_ilceNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> isVisible {
            get {
                return this.isVisibleField;
            }
            set {
                if ((this.isVisibleField.Equals(value) != true)) {
                    this.isVisibleField = value;
                    this.RaisePropertyChanged("isVisible");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KulupGuvenlikBilgileri", Namespace="http://schemas.datacontract.org/2004/07/UniversityCommunities.Models")]
    [System.SerializableAttribute()]
    public partial class KulupGuvenlikBilgileri : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KGuvenlikIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KullaniciAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> KulupIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UniversityCommunities.ServiceReference1.KulupKayit KulupKayitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SifreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> isVisibleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KGuvenlikId {
            get {
                return this.KGuvenlikIdField;
            }
            set {
                if ((this.KGuvenlikIdField.Equals(value) != true)) {
                    this.KGuvenlikIdField = value;
                    this.RaisePropertyChanged("KGuvenlikId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KullaniciAdi {
            get {
                return this.KullaniciAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.KullaniciAdiField, value) != true)) {
                    this.KullaniciAdiField = value;
                    this.RaisePropertyChanged("KullaniciAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> KulupId {
            get {
                return this.KulupIdField;
            }
            set {
                if ((this.KulupIdField.Equals(value) != true)) {
                    this.KulupIdField = value;
                    this.RaisePropertyChanged("KulupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UniversityCommunities.ServiceReference1.KulupKayit KulupKayit {
            get {
                return this.KulupKayitField;
            }
            set {
                if ((object.ReferenceEquals(this.KulupKayitField, value) != true)) {
                    this.KulupKayitField = value;
                    this.RaisePropertyChanged("KulupKayit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sifre {
            get {
                return this.SifreField;
            }
            set {
                if ((object.ReferenceEquals(this.SifreField, value) != true)) {
                    this.SifreField = value;
                    this.RaisePropertyChanged("Sifre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> isVisible {
            get {
                return this.isVisibleField;
            }
            set {
                if ((this.isVisibleField.Equals(value) != true)) {
                    this.isVisibleField = value;
                    this.RaisePropertyChanged("isVisible");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KulupLogo", Namespace="http://schemas.datacontract.org/2004/07/UniversityCommunities.Models")]
    [System.SerializableAttribute()]
    public partial class KulupLogo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UniversityCommunities.ServiceReference1.KulupKayit KulupKayitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Kulup_NoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Logo_AdresiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UniversityCommunities.ServiceReference1.KulupKayit KulupKayit {
            get {
                return this.KulupKayitField;
            }
            set {
                if ((object.ReferenceEquals(this.KulupKayitField, value) != true)) {
                    this.KulupKayitField = value;
                    this.RaisePropertyChanged("KulupKayit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Kulup_No {
            get {
                return this.Kulup_NoField;
            }
            set {
                if ((this.Kulup_NoField.Equals(value) != true)) {
                    this.Kulup_NoField = value;
                    this.RaisePropertyChanged("Kulup_No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Logo_Adresi {
            get {
                return this.Logo_AdresiField;
            }
            set {
                if ((object.ReferenceEquals(this.Logo_AdresiField, value) != true)) {
                    this.Logo_AdresiField = value;
                    this.RaisePropertyChanged("Logo_Adresi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Uyeler", Namespace="http://schemas.datacontract.org/2004/07/UniversityCommunities.Models")]
    [System.SerializableAttribute()]
    public partial class Uyeler : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UniversityCommunities.ServiceReference1.Bolumler BolumlerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UniversityCommunities.ServiceReference1.Fakulteler FakultelerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UniversityCommunities.ServiceReference1.KulupKayit KulupKayitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Kulup_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Unvan_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UniversityCommunities.ServiceReference1.UyeUnvanlari UyeUnvanlariField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Uye_AdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Uye_BolumNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> Uye_DogumTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Uye_EPostaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Uye_FakulteNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Uye_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Uye_OkulNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Uye_SoyadiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Uye_TelefonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> isVisibleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UniversityCommunities.ServiceReference1.Bolumler Bolumler {
            get {
                return this.BolumlerField;
            }
            set {
                if ((object.ReferenceEquals(this.BolumlerField, value) != true)) {
                    this.BolumlerField = value;
                    this.RaisePropertyChanged("Bolumler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UniversityCommunities.ServiceReference1.Fakulteler Fakulteler {
            get {
                return this.FakultelerField;
            }
            set {
                if ((object.ReferenceEquals(this.FakultelerField, value) != true)) {
                    this.FakultelerField = value;
                    this.RaisePropertyChanged("Fakulteler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UniversityCommunities.ServiceReference1.KulupKayit KulupKayit {
            get {
                return this.KulupKayitField;
            }
            set {
                if ((object.ReferenceEquals(this.KulupKayitField, value) != true)) {
                    this.KulupKayitField = value;
                    this.RaisePropertyChanged("KulupKayit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Kulup_Id {
            get {
                return this.Kulup_IdField;
            }
            set {
                if ((this.Kulup_IdField.Equals(value) != true)) {
                    this.Kulup_IdField = value;
                    this.RaisePropertyChanged("Kulup_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Unvan_Id {
            get {
                return this.Unvan_IdField;
            }
            set {
                if ((this.Unvan_IdField.Equals(value) != true)) {
                    this.Unvan_IdField = value;
                    this.RaisePropertyChanged("Unvan_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UniversityCommunities.ServiceReference1.UyeUnvanlari UyeUnvanlari {
            get {
                return this.UyeUnvanlariField;
            }
            set {
                if ((object.ReferenceEquals(this.UyeUnvanlariField, value) != true)) {
                    this.UyeUnvanlariField = value;
                    this.RaisePropertyChanged("UyeUnvanlari");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uye_Adi {
            get {
                return this.Uye_AdiField;
            }
            set {
                if ((object.ReferenceEquals(this.Uye_AdiField, value) != true)) {
                    this.Uye_AdiField = value;
                    this.RaisePropertyChanged("Uye_Adi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Uye_BolumNo {
            get {
                return this.Uye_BolumNoField;
            }
            set {
                if ((this.Uye_BolumNoField.Equals(value) != true)) {
                    this.Uye_BolumNoField = value;
                    this.RaisePropertyChanged("Uye_BolumNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Uye_DogumTarihi {
            get {
                return this.Uye_DogumTarihiField;
            }
            set {
                if ((this.Uye_DogumTarihiField.Equals(value) != true)) {
                    this.Uye_DogumTarihiField = value;
                    this.RaisePropertyChanged("Uye_DogumTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uye_EPosta {
            get {
                return this.Uye_EPostaField;
            }
            set {
                if ((object.ReferenceEquals(this.Uye_EPostaField, value) != true)) {
                    this.Uye_EPostaField = value;
                    this.RaisePropertyChanged("Uye_EPosta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Uye_FakulteNo {
            get {
                return this.Uye_FakulteNoField;
            }
            set {
                if ((this.Uye_FakulteNoField.Equals(value) != true)) {
                    this.Uye_FakulteNoField = value;
                    this.RaisePropertyChanged("Uye_FakulteNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Uye_Id {
            get {
                return this.Uye_IdField;
            }
            set {
                if ((this.Uye_IdField.Equals(value) != true)) {
                    this.Uye_IdField = value;
                    this.RaisePropertyChanged("Uye_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uye_OkulNo {
            get {
                return this.Uye_OkulNoField;
            }
            set {
                if ((object.ReferenceEquals(this.Uye_OkulNoField, value) != true)) {
                    this.Uye_OkulNoField = value;
                    this.RaisePropertyChanged("Uye_OkulNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uye_Soyadi {
            get {
                return this.Uye_SoyadiField;
            }
            set {
                if ((object.ReferenceEquals(this.Uye_SoyadiField, value) != true)) {
                    this.Uye_SoyadiField = value;
                    this.RaisePropertyChanged("Uye_Soyadi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uye_Telefon {
            get {
                return this.Uye_TelefonField;
            }
            set {
                if ((object.ReferenceEquals(this.Uye_TelefonField, value) != true)) {
                    this.Uye_TelefonField = value;
                    this.RaisePropertyChanged("Uye_Telefon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> isVisible {
            get {
                return this.isVisibleField;
            }
            set {
                if ((this.isVisibleField.Equals(value) != true)) {
                    this.isVisibleField = value;
                    this.RaisePropertyChanged("isVisible");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bolumler", Namespace="http://schemas.datacontract.org/2004/07/UniversityCommunities.Models")]
    [System.SerializableAttribute()]
    public partial class Bolumler : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Bolum_AdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Bolum_NoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Fakulte_NoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UniversityCommunities.ServiceReference1.Fakulteler FakultelerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UniversityCommunities.ServiceReference1.Uyeler[] UyelerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bolum_Adi {
            get {
                return this.Bolum_AdiField;
            }
            set {
                if ((object.ReferenceEquals(this.Bolum_AdiField, value) != true)) {
                    this.Bolum_AdiField = value;
                    this.RaisePropertyChanged("Bolum_Adi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Bolum_No {
            get {
                return this.Bolum_NoField;
            }
            set {
                if ((this.Bolum_NoField.Equals(value) != true)) {
                    this.Bolum_NoField = value;
                    this.RaisePropertyChanged("Bolum_No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Fakulte_No {
            get {
                return this.Fakulte_NoField;
            }
            set {
                if ((this.Fakulte_NoField.Equals(value) != true)) {
                    this.Fakulte_NoField = value;
                    this.RaisePropertyChanged("Fakulte_No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UniversityCommunities.ServiceReference1.Fakulteler Fakulteler {
            get {
                return this.FakultelerField;
            }
            set {
                if ((object.ReferenceEquals(this.FakultelerField, value) != true)) {
                    this.FakultelerField = value;
                    this.RaisePropertyChanged("Fakulteler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UniversityCommunities.ServiceReference1.Uyeler[] Uyeler {
            get {
                return this.UyelerField;
            }
            set {
                if ((object.ReferenceEquals(this.UyelerField, value) != true)) {
                    this.UyelerField = value;
                    this.RaisePropertyChanged("Uyeler");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UyeUnvanlari", Namespace="http://schemas.datacontract.org/2004/07/UniversityCommunities.Models")]
    [System.SerializableAttribute()]
    public partial class UyeUnvanlari : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Unvan_AdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Unvan_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UniversityCommunities.ServiceReference1.Uyeler[] UyelerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unvan_Adi {
            get {
                return this.Unvan_AdiField;
            }
            set {
                if ((object.ReferenceEquals(this.Unvan_AdiField, value) != true)) {
                    this.Unvan_AdiField = value;
                    this.RaisePropertyChanged("Unvan_Adi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Unvan_Id {
            get {
                return this.Unvan_IdField;
            }
            set {
                if ((this.Unvan_IdField.Equals(value) != true)) {
                    this.Unvan_IdField = value;
                    this.RaisePropertyChanged("Unvan_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UniversityCommunities.ServiceReference1.Uyeler[] Uyeler {
            get {
                return this.UyelerField;
            }
            set {
                if ((object.ReferenceEquals(this.UyelerField, value) != true)) {
                    this.UyelerField = value;
                    this.RaisePropertyChanged("Uyeler");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Saatler", Namespace="http://schemas.datacontract.org/2004/07/UniversityCommunities.Models")]
    [System.SerializableAttribute()]
    public partial class Saatler : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SaatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Saat {
            get {
                return this.SaatField;
            }
            set {
                if ((object.ReferenceEquals(this.SaatField, value) != true)) {
                    this.SaatField = value;
                    this.RaisePropertyChanged("Saat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IUniServis")]
    public interface IUniServis {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniServis/GetAuditoriums", ReplyAction="http://tempuri.org/IUniServis/GetAuditoriumsResponse")]
        UniversityCommunities.ServiceReference1.KonferansSalonlari[] GetAuditoriums();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniServis/GetAuditoriums", ReplyAction="http://tempuri.org/IUniServis/GetAuditoriumsResponse")]
        System.Threading.Tasks.Task<UniversityCommunities.ServiceReference1.KonferansSalonlari[]> GetAuditoriumsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniServis/GetTimes", ReplyAction="http://tempuri.org/IUniServis/GetTimesResponse")]
        UniversityCommunities.ServiceReference1.Saatler[] GetTimes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniServis/GetTimes", ReplyAction="http://tempuri.org/IUniServis/GetTimesResponse")]
        System.Threading.Tasks.Task<UniversityCommunities.ServiceReference1.Saatler[]> GetTimesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniServis/GetFaculties", ReplyAction="http://tempuri.org/IUniServis/GetFacultiesResponse")]
        UniversityCommunities.ServiceReference1.Fakulteler[] GetFaculties();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniServis/GetFaculties", ReplyAction="http://tempuri.org/IUniServis/GetFacultiesResponse")]
        System.Threading.Tasks.Task<UniversityCommunities.ServiceReference1.Fakulteler[]> GetFacultiesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUniServisChannel : UniversityCommunities.ServiceReference1.IUniServis, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UniServisClient : System.ServiceModel.ClientBase<UniversityCommunities.ServiceReference1.IUniServis>, UniversityCommunities.ServiceReference1.IUniServis {
        
        public UniServisClient() {
        }
        
        public UniServisClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UniServisClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UniServisClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UniServisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UniversityCommunities.ServiceReference1.KonferansSalonlari[] GetAuditoriums() {
            return base.Channel.GetAuditoriums();
        }
        
        public System.Threading.Tasks.Task<UniversityCommunities.ServiceReference1.KonferansSalonlari[]> GetAuditoriumsAsync() {
            return base.Channel.GetAuditoriumsAsync();
        }
        
        public UniversityCommunities.ServiceReference1.Saatler[] GetTimes() {
            return base.Channel.GetTimes();
        }
        
        public System.Threading.Tasks.Task<UniversityCommunities.ServiceReference1.Saatler[]> GetTimesAsync() {
            return base.Channel.GetTimesAsync();
        }
        
        public UniversityCommunities.ServiceReference1.Fakulteler[] GetFaculties() {
            return base.Channel.GetFaculties();
        }
        
        public System.Threading.Tasks.Task<UniversityCommunities.ServiceReference1.Fakulteler[]> GetFacultiesAsync() {
            return base.Channel.GetFacultiesAsync();
        }
    }
}
