//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityCommunities.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UniversiteKulupYonetimDBEntities : DbContext
    {
        public UniversiteKulupYonetimDBEntities()
            : base("name=UniversiteKulupYonetimDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bolumler> Bolumler { get; set; }
        public virtual DbSet<Fakulteler> Fakulteler { get; set; }
        public virtual DbSet<KulupEtkinlikFotograflari> KulupEtkinlikFotograflari { get; set; }
        public virtual DbSet<KulupEtkinlikleri> KulupEtkinlikleri { get; set; }
        public virtual DbSet<KulupGuvenlikBilgileri> KulupGuvenlikBilgileri { get; set; }
        public virtual DbSet<KulupKayit> KulupKayit { get; set; }
        public virtual DbSet<KulupLogo> KulupLogo { get; set; }
        public virtual DbSet<Universite_Duyuru> Universite_Duyuru { get; set; }
        public virtual DbSet<UniversiteKayit> UniversiteKayit { get; set; }
        public virtual DbSet<Uyeler> Uyeler { get; set; }
        public virtual DbSet<EtkinlikTurleri> EtkinlikTurleri { get; set; }
        public virtual DbSet<FaaliyetTurleri> FaaliyetTurleri { get; set; }
        public virtual DbSet<UyeUnvanlari> UyeUnvanlari { get; set; }
        public virtual DbSet<Saatler> Saatler { get; set; }
        public virtual DbSet<KonferansSalonlari> KonferansSalonlari { get; set; }
        public virtual DbSet<SalonTakvimi> SalonTakvimi { get; set; }
    }
}
