//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityCommunities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KonferansSalonlari
    {
        public int id { get; set; }
        public string SalonAdi { get; set; }
        public Nullable<int> SalonFakultesi { get; set; }
        public Nullable<short> Kontenjan { get; set; }
    
        public virtual Fakulteler Fakulteler { get; set; }
        public virtual SalonTakvimi SalonTakvimi { get; set; }
    }
}
