//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityCommunities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KulupEtkinlikFotograflari
    {
        public int FotoId { get; set; }
        public Nullable<int> EtkinlikId { get; set; }
        public string FotoURL { get; set; }
        public string FotoBaşlık { get; set; }
        public string FotoAçıklama { get; set; }
        public Nullable<bool> isVisible { get; set; }
    
        public virtual KulupEtkinlikleri KulupEtkinlikleri { get; set; }
    }
}
