//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityCommunities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KulupLogo
    {
        public int id { get; set; }
        public Nullable<int> Kulup_No { get; set; }
        public string Logo_Adresi { get; set; }
    
        public virtual KulupKayit KulupKayit { get; set; }
    }
}
