//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityCommunities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uyeler
    {
        public int Uye_Id { get; set; }
        public string Uye_OkulNo { get; set; }
        public string Uye_Adi { get; set; }
        public string Uye_Soyadi { get; set; }
        public Nullable<System.DateTime> Uye_DogumTarihi { get; set; }
        public Nullable<int> Uye_FakulteNo { get; set; }
        public Nullable<int> Uye_BolumNo { get; set; }
        public string Uye_EPosta { get; set; }
        public string Uye_Telefon { get; set; }
        public Nullable<int> Unvan_Id { get; set; }
        public Nullable<bool> isVisible { get; set; }
        public Nullable<int> Kulup_Id { get; set; }
    
        public virtual Bolumler Bolumler { get; set; }
        public virtual Fakulteler Fakulteler { get; set; }
        public virtual KulupKayit KulupKayit { get; set; }
        public virtual UyeUnvanlari UyeUnvanlari { get; set; }
    }
}
